# Generated by Django 3.2.4 on 2021-06-26 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='image',
            field=models.ImageField(upload_to='img', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='telefono',
            field=models.IntegerField(max_length=12, verbose_name='Telefono'),
        ),
    ]
