# Generated by Django 3.2.4 on 2021-06-26 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210626_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='telefono',
            field=models.IntegerField(verbose_name='Telefono'),
        ),
    ]
