# Generated by Django 3.2.4 on 2021-06-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_colaborador_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='rutColaborador',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut de Colaborador'),
        ),
    ]
